fixtures:
  symlinks:
    sentry: "#{source_dir}"
  forge_modules:
    apache: "puppetlabs/apache"
    concat: "puppetlabs/concat"
    logrotate: "puppet/logrotate"
    python: "stankevich/python"
    stdlib: "puppetlabs/stdlib"
    epel: "stahnma/epel"
