---

sudo: false
language: ruby
cache: bundler
script: bundle exec rake validate lint spec

matrix:
  fast_finish: true
  include:
  - rvm: 2.2.2
    env: PUPPET_GEM_VERSION="~> 4.0" BEAKER_debug=true
    script: bundle exec rake beaker
    services: docker
    sudo: required
